name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install JS dependencies
        run: |
          if [ -f yarn.lock ]; then
            corepack enable
            corepack prepare yarn@stable --activate
            # Try strict install first; if lockfile is out of sync, fall back to non-immutable
            yarn install --immutable --immutable-cache || yarn install
          elif [ -f package-lock.json ]; then
            # Prefer clean install; if out of sync, fall back to regular install
            npm ci || npm install
          else
            npm install
          fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make Gradle wrapper executable
        working-directory: android
        run: chmod +x ./gradlew

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew --no-daemon clean assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android/app/build/outputs/apk/debug/*.apk


